#!/usr/bin/env bash
set -euo pipefail

TAG="${1:?release tag is required}"
VERSION="${TAG#v}"
NOTES_FILE="${RUNNER_TEMP:-/tmp}/release-notes-${TAG}.md"
CURRENT_FILE="${RUNNER_TEMP:-/tmp}/release-notes-current-${TAG}.md"

if ! command -v gh >/dev/null 2>&1; then
  echo "::error::GitHub CLI is required to sync release notes"
  exit 1
fi

extract_changelog() {
  python3 - "$VERSION" <<'PY'
import pathlib
import re
import sys

version = sys.argv[1]
path = pathlib.Path("CHANGELOG.md")
if not path.exists():
    sys.exit(2)

text = path.read_text(encoding="utf-8")
heading = re.compile(r"^##\s+(?:\[)?v?" + re.escape(version) + r"(?:\])?(?:\s+-\s+.*)?\s*$", re.MULTILINE)
match = heading.search(text)
if not match:
    sys.exit(2)

next_heading = re.search(r"^##\s+", text[match.end():], re.MULTILINE)
end = match.end() + next_heading.start() if next_heading else len(text)
body = text[match.end():end].strip()
if not body:
    sys.exit(2)
print(body)
PY
}

normalize_existing_body() {
  python3 - "$CURRENT_FILE" "$TAG" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
tag = sys.argv[2]
body = path.read_text(encoding="utf-8") if path.exists() else ""
body = body.replace("\r\n", "\n").strip()

if not body:
    print(f"Release {tag}")
    sys.exit(0)

# GitHub autogenerated notes use this heading. Keep the first section and drop later duplicates.
pattern = re.compile(r"(?m)^##\s+What's Changed\s*$")
matches = list(pattern.finditer(body))
if len(matches) <= 1:
    print(body)
    sys.exit(0)

first = matches[0]
second = matches[1]
print((body[:second.start()].rstrip()).strip())
PY
}

if extract_changelog > "$NOTES_FILE"; then
  echo "Using CHANGELOG.md section for ${TAG}."
else
  echo "No CHANGELOG.md section found for ${TAG}; normalizing the existing release body."
  gh release view "$TAG" --json body --jq '.body // ""' > "$CURRENT_FILE"
  normalize_existing_body > "$NOTES_FILE"
fi

gh release edit "$TAG" --notes-file "$NOTES_FILE"
echo "Release notes synced for ${TAG}."
